title: Eric Liu
logo: /assets/img/2023_ericliu.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: jeykll-theme-minimal
